services:
  - type: web
    name: django-todo-app
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip --no-cache-dir
      pip install --no-cache-dir -r requirements.txt
      python manage.py collectstatic --noinput --verbosity 0
      python manage.py makemessages -l en --verbosity 0 || echo "Messages creation skipped"
      python manage.py makemessages -l ja --verbosity 0 || echo "Messages creation skipped"
      python manage.py compilemessages --verbosity 0 || echo "Messages compilation skipped"
    startCommand: |
      chmod +x startup_monitor.sh && ./startup_monitor.sh
    healthCheckPath: /accounts/login/
    envVars:
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE  
        value: 1
      - key: RENDER
        value: true