services:
  - type: web
    name: django-todo-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py makemessages -l en
      python manage.py makemessages -l ja
      python manage.py compilemessages
      python manage.py collectstatic --noinput
    startCommand: gunicorn todo_app.wsgi:application